### ISSUE TITLE
List() for a single file on sharepoint server not working

### ISSUE THREAD

**Issue by on-delete** [lookfirst/sardine#191]
Hello,

i tried to receive a single DavRessource for a file on a sharepoint server. But this is not working, i always get the error message 404 file not found. But if i perform a list() on the directory of the file, the file is found correctly.

So i don't exactly know, if this is a sharepoint problem, or the sardine api looks for an directory instead of a single file. Because in the response from the sharepoint server it says, that the directory is not found.

I also performed an exists() on the file and it returned true.

**Comment by on-delete** [comment]
any new idea for my problem? :)

**Comment by lookfirst** [comment]
As I said above, try to get the easiest case working first. Then start adding edges.

**Comment by on-delete** [comment]
I already tried it with simple links. If this would be the problem, then the get() would also not work.

**Comment by lookfirst** [comment]
The only log and code output that I've seen is what you've shown above. I can't read your mind and I'm not sitting there next to you to help you. So, until you give full details for things, I'm sorry, there isn't much I can do to help you. 

Since this is now turning into a discussion and less of a bug report, I'm going to close this issue and if you'd like to try to bring this up on the sardine google group (or stack overflow) to get outside help, you are welcome to do so.
