### ISSUE TITLE
Does Sardine support SNI?

### ISSUE THREAD

**Issue by NitishDeshpande** [lookfirst/sardine#309]
I am using Sardine to list files on WebDAV and download them one by one. Going forward, the WebDAV server is going to mandate the clients to use SNI (Server Name Indication). Does Sardine support SNI?

Thanks in advance.

**Comment by lookfirst** [comment]
Sardine depends on Apache HttpComponents to do its network communications, so as long as that works, it should work. Googling around, it appears as though it is supported automatically in JDK7+. I think the answer is... try it, if it doesn't work, then google around for the answer to tweaking HttpComponents. If you feel up for it, contribute back to the SetupGuide wiki document (or here) some instructions so that others can benefit. =)

I'm going to close this issue for now though since this is really better off as a SO question. Thanks!
