### ISSUE TITLE
sardine.createDirectory(url)?

### ISSUE THREAD

**Issue by dkocher** [lookfirst/sardine#59]
_Original author: zu...@7dian.com (July 07, 2010 08:30:27)_

import com.googlecode.sardine.Sardine;
import com.googlecode.sardine.SardineFactory;

public class MySardine {

```
private String webDavUrl = &quot;&quot;;
private Sardine sardine= null;

/**
 * constructed function
 * @param webDavUrl eg：http://10.189.8.103:8888/uploads/
 * @param name
 * @param passwd
 * @throws Exception
 */
public MySardine(String webDavUrl, String name, String passwd) throws Exception
{
    this.webDavUrl = webDavUrl;
    sardine = SardineFactory.begin(name, passwd);
    //sardine = SardineFactory.begin();
}


/**
 * create webdav server folder
 * @param eg: pics/test/2010
 * @throws Exception
 */
public void createFolder(String desUrl) throws Exception
{
    String[] folders = this.getFolders(desUrl);
    if(null != folders)
    {
        String davFolder = &quot;&quot;;
        int length = folders.length;

        for(int i = 0; i &lt; length; i++)
        {
            davFolder = this.webDavUrl + folders[i];

            boolean exists = sardine.exists(davFolder);

            if(!exists)
                sardine.createDirectory(davFolder);
        }

    }
}

/**
 * convert desurl to uls array，eg：“pic/user/2010”=&gt;[&quot;pic&quot;,&quot;pic/user&quot;,&quot;pic/user/2010&quot;]
 * @param desUrl eg:“pic/user/2010”
 * @return [&quot;pic&quot;,&quot;pic/user&quot;,&quot;pic/user/2010&quot;]
 * @throws Exception
 */
private String[] getFolders(String desUrl) throws Exception
{
    if(null == desUrl || desUrl.length() == 0)
        return null;

    String[] folder = desUrl.split(&quot;/&quot;);
    String[] folders = new String[folder.length];
    for(int i = 0; i &lt; folder.length; i ++)
    {
        if(i == 0)
            folders[i] = folder[i];
        else
            folders[i] = folders[i-1] + &quot;/&quot; +folder[i];
    }
    return folders;
}

/**
 * @param args
 */
public static void main(String[] args) {
    try
    {           
        MySardine mns = new MySardine(&quot;http://10.189.8.103:8888/uploads/&quot;,&quot;dav@test.com&quot;, &quot;1qaz@WSX&quot;);

        mns.createFolder(&quot;2010/pic/new/dev&quot;);
    }
    catch(Exception ex)
    {
        ex.printStackTrace();
    }

}
```

}
# 

in main function,
&quot;http://10.189.8.103:8888/uploads/&quot; is my apache webdav server;
&quot;2010/pic/new/dev&quot; is  the folders I need to create；

but，
it only create &quot;2010&quot; and &quot;pic&quot;  on my server，
then process is hanged。
# 

why ?

_Original issue: http://code.google.com/p/sardine/issues/detail?id=59_

**Comment by missfeldt** [comment]
I see this is old and closed, but I just ran into the same 403 issue lately. It doesn't matter if I connect to a public webdav test server or to our internal company server. Both do the same if I send a Sardine.exists(DIRECTORY):
- If the directory doesn't exist, it returns 404 Not Found -> false -> that's ok
- If the directory exists, the server returns 403 Forbidden -> SardineException -> that's not ok
I don't know why wedav servers have such a behaviour with a HEAD against a directory, but it seems quite common.
I saw that Sardine refactored the code to use a ExistsResponseHandler. That sounds fine. The only thing I need is to exchange this handler with another version that takes the 403 into account. But sadly SardineImpl doesn't allow those handlers to be customized. Could you please change this? Same problem in the SardineFactory - it chooses the one and only Impl, not letting me register my own subclass. It would be very easy to let the users customize everything if the instance creations were not fixed in the code.
